version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db/metabase.db
    volumes:
      - metabase_data:/metabase.db
    restart: always

volumes:
  metabase_data:
